### PR TITLE
Add tests and fix error for getdelegate

### PR DESCRIPTION
**Pull request by blegat**
@chriscoey @joehuchette @rdeits Any objection to tag v0.2.0 once this PR is merged ? We need to tag v0.2.0 and not just v0.1.1 since it drops `@polyconstraint` and `@polyvariable` that have been deprecated in v0.1.0.

### CODE REVIEW

**Comment by chriscoey** [comment]
looks good!

**Comment by chriscoey** [comment]
what about #18 - is it worth trying to merge that before the release?

**Comment by blegat** [comment]
Yes, we can tag the release once #18 is merged if you are willing to get this through.
I remember there was the issue mentionned in https://github.com/JuliaOpt/PolyJuMP.jl/pull/18#issuecomment-354539082 and the tests on https://github.com/JuliaOpt/SumOfSquares.jl/pull/32 are currently failing but once this is resolved, we can merge #18

**Comment by chriscoey** [comment]
I'm in Thailand for another week without the ability to run anything. @joehuchette might be busy thesising, not sure. No need to delay the release.

**Pull request merged**
